### ISSUE TITLE
Allow to programmatically fit the page 

### ISSUE THREAD

**Issue by popod** [sayanee/angularjs-pdf#173]
Is there a way to programmatically call the fit() function of angularjs-pdf directive from my controller ? If not, could this be implemented ?

Thanks

**Comment by dennybiasiolli** [comment]
Hi @popod,
thanks and sorry for the late answer.
Good news! In the current version of the directive you can call the `fit()` function in your controller's scope because the directive's scope is not isolated.
This is good for you, but we are working on a new version that isolate the directive's scope, stay tuned. 😄

**Comment by popod** [comment]
Okey thanks for answer
