### ISSUE TITLE
Error: No PDFJS.workerSrc specified

### ISSUE THREAD

**Issue by jenikaur** [sayanee/angularjs-pdf#199]

**Comment by dennybiasiolli** [comment]
Can you provide more info about your error?

**Comment by jaime-ez** [comment]
Hi, I encountered a similar error. For what I could isolate pdf.js has some issues when calling the worker. For instance if I use pdf.min.js it will look for pdf.min.worker.js (instead of pdf.worker.min.js) and thus a PDFJS.workerSrc error is emitted.
This happens also after the build step for my bower deps where all files are uglified and concat into one scripts.FILEREVNUMBER.js file, thus pdf.js will look for pdf.FILEREVNUMBER.worker.js (file not found error) instead of looking in the same file path.

My workaround was to remove pdf.js from bower deps and get it from a cdn (the non minified version).
I think angularjs-pdf could benefit from not using pdf.js as a bower dependency and just call it from a cdn, or maybe updating the bower dep to a more recent pdf.js version that probably does not have this issue (haven't looked in it).

Those are my two cents on this issue, hope it helps!

**Comment by jenikaur** [comment]
Thanks for the help but resolved the issue by including the file for
pdfjsworker.




Regards
