### ISSUE TITLE
Cross-domain

### ISSUE THREAD

**Issue by Wooleners** [sayanee/angularjs-pdf#25]
Pdf file when I use a cross-domain configuration it is there？

**Comment by ertanden** [comment]
The problem is when trying to view a file which is stored in another domain (example: Amazon S3) than your web site. 

Browsers does not allow this... Sometimes we need to add special headers to the HTTP request in order for cross-domain requests to work. Is it possible to customize headers for the GET request?

**Comment by simobasso** [comment]
Hi @ertanden, 

you can do it using cors:
http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

I hope this help you:
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request
