### ISSUE TITLE
PDF fuzzy on retina

### ISSUE THREAD

**Issue by rwwagner90** [sayanee/angularjs-pdf#53]
I already have fixed this locally, so I can submit a PR, if you'd like. You're welcome to fix it yourself if you would rather too.

**Comment by sayanee** [comment]
wow! thanks - yes please send a PDF :+1:

**Comment by rwwagner90** [comment]
I assume by PDF you mean PR? :stuck_out_tongue: 

I will try to clean it up and submit something this week.

**Comment by sayanee** [comment]
LOL yes, please send a pull request :stuck_out_tongue_closed_eyes:

**Comment by rwwagner90** [comment]
I actually looked at my retina support commit, and it might be good as is. I submitted a PR. Please let me know your thoughts and I'll be glad to make an necessary changes.

**Comment by ElRoberto538** [comment]
Hi guys, I have noticed that this PR results in a blurry canvas due to the dimensions being set to decimal values e.g. 1024.3456. When both the canvas dimensions and the style dimensions are set to this value the canvas dimensions appear to be truncated but the style dimensions will stay as a number containing decimals and so they won't match - this results in blurring (tested on 1080p monitor in Chrome and Firefox).

I have patched this locally by changing the following lines within the new `setCanvasDimensions()` method:

```Javascript
canvas.style.width = w + 'px';
canvas.style.height = h + 'px';
```
to:
```Javascript
canvas.style.width = Math.trunc(w) + 'px';
canvas.style.height = Math.trunc(h) + 'px';
```

With this patch the canvas appears normally - note I haven't tested on a retina screen as I don't have one with me at the moment.

**Comment by sayanee** [comment]
Thanks @ElRoberto538! Could you send us a pull request to the changes in this file `example/js/directives/angular-pdf.js`? Also do you have a sample pdf page? 

I have a retina screen that I can test on.

**Comment by ElRoberto538** [comment]
No problem, I will create a pull request later today - I will also find a suitable sample PDF to demonstrate the fix.

**Comment by rwwagner90** [comment]
Good catch @ElRoberto538. I have a retina screen, I'd be glad to check it out. Let me know when a PR is up.

**Comment by sayanee** [comment]
@rwwagner90 - it's here: https://github.com/sayanee/angularjs-pdf/pull/56

thanks everyone :star2:
